apiVersion: v1
kind: Service
metadata:
  name: model-broker-service
  namespace: understudy
spec:
  selector:
    app: model-broker
  ports:
    - name: http
      port: 8003
      targetPort: 8003
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-broker
  namespace: understudy
spec:
  replicas: 1  # Single replica to manage model storage
  selector:
    matchLabels:
      app: model-broker
  template:
    metadata:
      labels:
        app: model-broker
    spec:
      containers:
      - name: model-broker
        image: bennyfriedman/understudy-model-broker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
        env:
        - name: MODEL_STORAGE_PATH
          value: /app/model_weights
        - name: PORT
          value: "8003"
        - name: HOST
          value: "0.0.0.0"
        volumeMounts:
        - name: model-weights
          mountPath: /app/model_weights
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
      volumes:
      - name: model-weights
        persistentVolumeClaim:
          claimName: model-weights-pvc