apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service
  namespace: understudy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: training-service
  namespace: understudy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: slm-manager
  namespace: understudy
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["create", "get", "list", "update", "delete", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "delete", "watch"]
- apiGroups: [""]
  resources: ["services", "pods", "pods/log"]
  verbs: ["create", "get", "list", "delete", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["create", "get", "update", "delete", "list"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-slm-manager
  namespace: understudy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: slm-manager
subjects:
- kind: ServiceAccount
  name: backend-service
  namespace: understudy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: training-slm-manager
  namespace: understudy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: slm-manager
subjects:
- kind: ServiceAccount
  name: training-service
  namespace: understudy